name: Bug Report
description: File a bug report
title: "<ðŸ› Bug>  "
labels: ["bug", "triage"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        # ðŸ¦‹ ðŸ¦‹ ðŸ¦‹   <<<   Bug Report   >>>  ðŸ¦‹ ðŸ¦‹ ðŸ¦‹ 

        > Thanks for taking the time to fill out this bug report! 
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! Please include any relavent screenshots of images, and the steps to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: dropdown
    id: user_impact
    attributes:
      label: How impactful is this bug?
      description: Let us know how impactful this bug is to you
      multiple: false
      options:
        - ðŸœ Minor annoyance
        - ðŸ¤” Notable but managable
        - ðŸ¤¯ Major disruption
        - ðŸš’ Showstopper 
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Example: Whenever I try to do xyz (1-2 times a week)"
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      multiple: false
      options:
        - Linux
        - MacOS
        - Windows -> WSL
        - Windows -> Linux VM
  - type: dropdown
    id: arch
    attributes:
      label: What system architecture are you running Taqueria on?
      description: You can find out by running `uname -m` in your terminal
      multiple: false
      options:
        - arm64 (M1 Macs)
        - x64
  - type: input
    id: taq_version
    attributes:
      label: What version of Taqueria are you using?
      description: You can find out by running `taq --version` in your terminal
      placeholder: ex. v0.12.1
    validations:
      required: false
  - type: input
    id: node_version
    attributes:
      label: What version of Node.js are you using?
      description: You can find out by running `node --version` in your terminal
      placeholder: ex. v16.16.0
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: If you would like to be followed up with about this, please provide a contact email
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ecadlabs/taqueria/blob/1d6476f92fce0f2f36cd268549aa15e6cbe770d3/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
