name: Dev Task
description: Adds a dev-task to the Taqueria dev scrum board
title: "[🚧 DevTask] ➾ "
labels: ["dev-task"]
assignees:
  - hu3man
body:
  - type: markdown
    attributes:
      value: |
        # 🚧 🚧 🚧   <><><>   Dev Task   <><><>   🚧 🚧 🚧 

        ## 🛑 Sanity Check: Does this really need it's own ticket?
  - type: input
    id: epic_link
    attributes:
      label: 🔗 Epic|Feature Link
      description: Link to the Epic or feature this task is related to
      placeholder: "ex. https://github.com/ecadlabs/taqueria/issues/123"
    validations:
      required: false
  - type: checkboxes
    id: status
    attributes: 
      label: 🚥 Definition of Done
      options:
        - label: "🎯 Planning and Design"
        - label: "🏎️ Dev Implementation"
        - label: "🏁 Test Plan Executed"
        - label: "🏛️ Documentation"
  - type: textarea
    id: to_do
    attributes:
      label: ✅ To Do
      description: A list of to do items for this ticket
      placeholder: "- [ ] 😎  Make Taqueria awesome \n- [ ] 🌮  Eat tacos "
    validations:
      required: false
  - type: textarea
    id: scope
    attributes:
      label: 🔭 Scope
      description: "Explicitly, what is in and out of scope for this ticket"
      value: "🏎️ In Scope: \n - [ ] ... \n \n 🙅‍♂️ Out of Scope: \n - [ ] ... \n \n "
  - type: textarea
    id: description
    attributes:
      label: 🧰 Work Description
      description: "Describe what needs to be done"
      placeholder: "In as much detail as possible, explain the work to be done. Include any architecture or design notes and the sequencing of each thing that needs to be done"
  - type: textarea
    id: ac
    attributes:
      label: 📋 Acceptance Criteria
      value: "✨ Features: \n- [ ] ... \n \n 📚 Documentation: \n- [ ] ... \n "
    validations:
      required: false
  - type: textarea
    id: test_plan
    attributes:
      label: 🥇 Test Plan
      description: "Describe how this will be tested"
      placeholder: "Include manual and automated testing"
    validations:
      required: false
  - type: input
    id: estimate
    attributes:
      label: 🐘 Sizing
      description: Estimate the time and effort required
      placeholder: "0"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ecadlabs/taqueria/blob/1d6476f92fce0f2f36cd268549aa15e6cbe770d3/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
