name: 🚧 Dev Task
description: Tickets for engineering and dev
title: "🚧 Dev ➾ "
labels: ["dev-task"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        # ◢▅◣◥▅◤◢▅◣ 🚧🚧🚧 Dev Task 🚧🚧🚧  ◢▅◣◥▅◤◢▅◣  

        ## 🛑 Sanity Check: Does this really need it's own ticket?

  - type: input
    id: epic_link
    attributes:
      label: 🔗 Epic|Feature Link
      placeholder: "ex. https://github.com/ecadlabs/taqueria/issues/123"
    validations:
      required: false
  - type: checkboxes
    id: status
    attributes: 
      label: 🚥 Definition of Done
      options:
        - label: "🎯 Planning and Design"
        - label: "🏎️ Dev Implementation"
        - label: "🛩️ Documentation Updated"
        - label: "🏟️ Peer / User Reviewed"
        - label: "🏁 Test Plan Validated"
        - label: "✍️ Release Notes Added"
        - label: "🏆 Product Approved"
  - type: textarea
    id: to_do
    attributes:
      label: ✅ To Do
      description: A list of to do items (and drivers) for this ticket
      placeholder: "- [ ] 😎  Make Taqueria awesome \n- [ ] 🌮  Eat tacos "
    validations:
      required: false
  - type: textarea
    id: ac
    attributes:
      label: ⚖️ Acceptance Criteria
      value: "✨ Functional: \n- [ ] ... \n \n 📐 Non-Functional: \n- [ ] ... \n "
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: 🔭 Scope
      description: "Explicitly, what is out of scope for this ticket"
      value: "🙅‍♂️ Out of Scope: \n- ... \n \n "
  - type: textarea
    id: description
    attributes:
      label: 🧰 Work Description
      description: "Describe what needs to be done"
      placeholder: "In as much detail as possible, explain the work to be done. Include any architecture or design notes and the sequencing of each thing that needs to be done"
  - type: input
    id: estimate
    attributes:
      label: 🦄 Sizing
      description: Estimate the time and effort required in days of effort using Fibonacci numbers (1,)
      placeholder: "0"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ecadlabs/taqueria/blob/1d6476f92fce0f2f36cd268549aa15e6cbe770d3/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
