name: Feature Request
description: Request a new feature
title: "[🚧 Feature]: "
labels: ["feature-request", "triage"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        This form creates a new Feature issue in the Taqueria inbox 
  - type: textarea
    id: problem_space
    attributes:
      label: Problem or Use Case
      description: Please tell us about what problem this feature solves or what value it provides
      placeholder: "Tell us about the use case for this feature and why it's important"
    validations:
      required: true
  - type: textarea
    id: feature-desc
    attributes:
      label: Feature Description
      description: Please provide details about how this would work
      placeholder: Tell us what you would like Taqueria to do! Include as much detail as possible including acceptance criteria
    validations:
      required: true
  - type: input
    id: epic_link
    attributes:
      label: Epic link
      description: Link to the Epic or feature this task is related to
      placeholder: ex. https://productboard.com/xyz
    validations:
      required: false
  - type: checkboxes
    id: status
    attributes: 
      label: status
      description: Implementation Status
      options:
        - label: 🔬 Feature design
        - label: 🧪 Testing Plan
        - label: 📚 Documentation
        - label: 🚀 Dev Implementation
        - label: 🤖 Automated Tests 
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ecadlabs/taqueria/blob/1d6476f92fce0f2f36cd268549aa15e6cbe770d3/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
