name: 🌋 Epic|Feature 
description: Product feature or epic 
title: "🌋 E|F ➾ "
labels: ["feature", "triage"]
assignees:
  - hu3man
body:
  - type: markdown
    attributes:
      value: |
          # ◢▅◣◥▅◤◢▅◣🏔️🌋⛰️ Epic|Feature ⛰️🌋🏔️◢▅◣◥▅◤◢▅◣

          ## 🛑 Sanity Check: Does this really need its own ticket?
 
  - type: input
    id: pb_link
    attributes:
      label: Product Board Link
      placeholder: "ex. https://productboard.com/..."
    validations:
      required: false
  - type: checkboxes
    id: tkt_status
    attributes: 
      label: 🚥 Status
      options:
        - label: 🔮 Product/Feature Design
        - label: ✍🏻 Architecture/Implementation Planning
        - label: 🏗️ Under Construction
        - label: ⛳ Feature Complete
        - label: ⛵ GTM / Release
  - type: textarea
    id: to_do
    attributes:
      label: ✅ To Do
      description: A list of to-do items for this ticket with drivers
      placeholder: "- [ ] 😎  Make Taqueria awesome (@person1) \n- [ ] 🌮  Eat tacos (@person2)"
    validations:
      required: false
  - type: textarea
    id: feature-desc
    attributes:
      label: 📐 Feature Description
      description: Please provide details about how this would work
      placeholder: Tell us what you would like Taqueria to do! Include as much detail as possible about how this would work and what the ux would be
    validations:
      required: true
  - type: textarea
    id: problem_space
    attributes:
      label: 🚩 Problem or Use Case
      description: Please tell us about what problem this feature solves or what value it provides
      placeholder: "Tell us about the use case for this feature and why it's important"
    validations:
      required: false
  - type: textarea
    id: ac
    attributes:
      label: ⚖️ Acceptance Criteria
      description: Define the definition of done for this feature
      value: "✨ Features: \n- [ ] ... \n \n 📚 Docs: \n- [ ] ... \n"
    validations:
      required: false
  - type: textarea
    id: scope
    attributes:
      label: 🔭 Scope
      description: "Explicitly, what is in and out of scope for this ticket"
      value: "🏎️ In Scope: \n- ... \n \n 🙅‍♂️ Out of Scope: \n- ... \n \n "
  - type: textarea
    id: related_issues
    attributes:
      label: 🔗  Related Issues and Subtasks
      description: Links to related issues on GitHub or Productboard
      placeholder: "- [ ] Issue [#123](...) \n- [ ] Issue [#123](...) "
    validations:
      required: false
  - type: input
    id: estimate
    attributes:
      label: 🦄 Sizing
      description: Estimate the time and effort required in days (Fibonacci sequence)
      placeholder: "0"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/pinnacle-labs/contrib/blob/main/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

