name: Feature Request
description: Request a new feature
title: "[Feature]: "
labels: ["feature-request", "triage"]
assignees:
  - hu3man
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem_space
    attributes:
      label: The Why?
      description: Please tell us about what problem this feature solves, or what value it adds
      placeholder: ""
      value: "Details about the problem your feature solves"
    validations:
      required: true
  - type: textarea
    id: feature-desc
    attributes:
      label: The What?
      description: Please provide details about your feature request
      placeholder: Tell us what you would like Taqueria to do!
      value: "Details about the feature request"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ecadlabs/taqueria/blob/1d6476f92fce0f2f36cd268549aa15e6cbe770d3/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
