name: Feature Request
description: Request a new feature
title: "[💡 Feature/Epic]: "
labels: ["feature-request", "triage"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ## 🌮 🌮 🌮  >>> Feature / Epic <<< 🌮 🌮 🌮  
  - type: input
    id: pb_link
    attributes:
      label: Product Board Link
      description: Link to the productboard feature this is related to
      placeholder: "ex. https://productboard.com/..."
    validations:
      required: false
  - type: checkboxes
    id: status
    attributes: 
      label: Ticket Status
      options:
        - label: 🔬 Feature Design
        - label: 🧪 Testing Plan
        - label: 🔪 Ticket Slicing
        - label: 🚀 Dev Implementation
        - label: 🤖 Automated Tests
  - type: textarea
    id: to_do
    attributes:
      label: To Do
      description: A list of to do items for this ticket
      value: "- [ ] 😎  Make Taqueria awesome \n- [ ] 🌮  Eat tacos "
    validations:
      required: true
  - type: textarea
    id: related_issues
    attributes:
      label: Related Issues
      description: Links to related issues
      value: "- [ ] Issue [#123](...) \n- [ ] Issue [#123](...) "
    validations:
      required: true
  - type: textarea
    id: feature-desc
    attributes:
      label: Feature Description
      description: Please provide details about how this would work
      placeholder: Tell us what you would like Taqueria to do! Include as much detail as possible about how this would work and what the ux would be
    validations:
      required: true
  - type: textarea
    id: problem_space
    attributes:
      label: Problem or Use Case
      description: Please tell us about what problem this feature solves or what value it provides
      placeholder: "Tell us about the use case for this feature and why it's important"
    validations:
      required: true
  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
      description: Requirements
      value: "### Feature \n- [ ] \n \n ### Documentation \n- [ ] New feature docs \n- [ ] Refactor existing docs \n- [ ] Release notes \n- [ ] "
    validations:
      required: true
  - type: input
    id: estimate
    attributes:
      label: Sizing
      description: Estimate the time and effort required
      placeholder: "0"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ecadlabs/taqueria/blob/1d6476f92fce0f2f36cd268549aa15e6cbe770d3/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
