#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run test:unit -w tests

# Update deno-lock file for CICD caching
deno cache --import-map ./import_map.json --lock ./deno-lock.json --lock-write index.ts
