#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run test:unit -w tests

## Process documentation files and add modified files to the git commit
npx ts-node ./parse-readme-template.ts
echo "Adding any modified doc files to the commit"
HUSKY=0 git ls-files **/*.md **/*.mdx --others --exclude-standard --modified| xargs git add 
