name: alex-cache

on: push

jobs:
  cache-brew-stuff:
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/Library/Caches/Homebrew/
            /usr/local/Cellar/
          key: macos-homebrew-123456

      - name: Install Dependencies if no cache found
        if: ${{ steps.cache.outputs.cache-hit }} != 'true'
        run: |
          brew install docker
          brew install colima
          colima start

      - name: ink dependencies if cache found
        if: ${{ steps.cache.outputs.cache-hit }} = 'true'
        run: |
          brew link docker
          brew link colima
          colima start
        
      - name: Check locations of stuff
        run: |
          ls -al ~/Library/Caches/Homebrew/








