name: binary tests

on:
  push:

env:
  DENO_DIR: ./deno

jobs:
  build_taqueria_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
       include:
         - os: ubuntu-latest
           deno_target: "x86_64-unknown-linux-gnu"
           extension: ""
         - os: windows-latest
           deno_target: "x86_64-pc-windows-msvc"
           extension: ".exe"
         - os: macOS-latest
           deno_target: "x86_64-apple-darwin"
           extension: ""

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "^1.0.0"

      - name: Build the binary for ${{ matrix.os }}
        env:
          DENO_TARGET: ${{ matrix.deno_target }}
          TAQ_COMMAND: taqueria${{ matrix.extension }}
        run: |
          deno compile --output taqueria --target $DENO_TARGET --allow-run --allow-write --allow-read --allow-env index.ts 
          mkdir ./test_project
          ./$TAQ_COMMAND --version
          ./$TAQ_COMMAND init -p ./test_project
          ls ./test_project

