name: binary tests

on:
  push:

env:
  DENO_DIR: ./deno

jobs:
  build_taqueria_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "^1.0.0"

      - name: Build the binary for ${{ matrix.os }}
        run: |
          deno compile --output taqueria --allow-run --allow-write --allow-read --allow-env index.ts 
          mkdir ./test_project
          ./taqueria --version
          ./taqueria init -p ./test_project
          ls -l ./test_project

