name: binary tests

on:
  push:

jobs:
  build_taqueria_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
       include:
         - os: ubuntu-latest
           deno_target: "x86_64-unknown-linux-gnu"
         - os: windows-latest
           deno_target: "x86_64-pc-windows-msvc"
         - os: macOS-latest
           deno_target: "x86_64-apple-darwin"

    env:
      DENO_DIR: ./deno
      DENO_TARGET: ${{ matrix.deno_target }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "^1.0.0"

      - name: Build the binary file ${{ matrix.os }}
        run: |
          deno compile --output taqueria --target $DENO_TARGET --allow-run --allow-write --allow-read --allow-env index.ts 
          mkdir ./test_project
          ./taqueria --version
          ./taqueria init -p ./test_project
          ls ./test_project
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Build the binary for ${{ matrix.os }}
        run: |
          deno compile --output taqueria --target %DENO_TARGET% --allow-run --allow-write --allow-read --allow-env index.ts 
          mkdir ./test_project
          ./taqueria.exe --version
          ./taqueria.exe init -p ./test_project
          ls ./test_project
        if: ${{ matrix.os == 'windows-latest' }}

