name: 'Build Binaries'

on:
  push:
    branches:
      - 'refactor_github_workflows'

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
       include:
         - os: ubuntu-latest
           os_short: ubuntu
           deno_target: "x86_64-unknown-linux-gnu"
           taqueria_bin: "taq"
         - os: windows-latest
           os_short: windows
           deno_target: "x86_64-pc-windows-msvc"
           taqueria_bin: "taq.exe"
         - os: macOS-latest
           os_short: macos
           deno_target: "x86_64-apple-darwin"
           taqueria_bin: "taq"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.23.4'
      - name: DEBUG
        shell: bash
        run: |
          TAQUERIA_BRANCH_INLINE=$(git rev-parse --abbrev-ref HEAD)
          TAQUERIA_COMMIT_INLINE=$(git rev-parse --short HEAD)

          echo "Debug env variable TAQUERIA_BRANCH_INLINE: ${TAQUERIA_BRANCH_INLINE}"
          echo "Debug env variable TAQUERIA_COMMIT_INLINE: ${TAQUERIA_COMMIT_INLINE}"

          npm run build:docker:debug
