name: List services in GCP
on:
  push:

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: gcp_auth
      name: gcp_auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/108868714658/locations/global/workloadIdentityPools/github-actions-storage-pool/providers/github-actions-oidc-provider
        service_account: github-storage-service-account@tez-ie.iam.gserviceaccount.com
    - id: gcloud_list_test
      name: gcloud_list_test
      run: |
        gcloud services list