name: issue-mover

on:
  issues:
    types: [opened, reopened]
  
  pull_request:
    branches:
      - main

jobs:
  dev-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/ecadlabs/projects/9
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: dev-task
          label-operator: OR
  
  other-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/ecadlabs/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: dev-task
          label-operator: NOT
