name: release-taqueria

on:
  create:
    tags:
      - v*

jobs:
  create-release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      upload-url: ${{ steps.create-release.outputs.upload-url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

  build-and-upload:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ${{ matrix.os }}
    needs: [create-release]
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            os_short: ubuntu
            deno_target: "x86_64-unknown-linux-gnu"
            taqueria_bin: "taqueria"
          - os: windows-latest
            os_short: windows
            deno_target: "x86_64-pc-windows-msvc"
            taqueria_bin: "taqueria.exe"
          - os: macOS-latest
            os_short: macos
            deno_target: "x86_64-apple-darwin"
            taqueria_bin: "taqueria"

    env:
      DENO_DIR: ./deno
      DENO_TARGET: ${{ matrix.deno_target }}
      TAQ_BIN:

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "^1.0.0"

      ## This job will compile the binary for the target OS. The binary is then tested by initializing a project called "test_project"
      ## If the initialization command output is equal to "Project taq'ified!" we know that the binary works for the given os, else the command exits with status code 1.
      - name: Build the binary for ${{ matrix.os }}
        id: build-bin
        shell: bash
        run: |
          deno compile --output taqueria --target $DENO_TARGET --allow-run --allow-write --allow-read --allow-env index.ts 
          [[ $(./"${{ matrix.taqueria_bin }}" init -p ./test_project) == "Project taq'ified!" ]] 
          mv "${{ matrix.taqueria_bin }}" "taqueria.${{ matrix.deno_target }}"

      - name: Upload release Assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload-url }}
          asset_path: ${{ github.workspace }}/${{ matrix.os }}/test
          asset_name: taqueria.${{ matrix.deno_target }}
          asset_content_type: application/octet-stream
