name: Taqueria Docker image
on:
  workflow_call:
    inputs:
      linux_binary_url:
        type: string
        required: true
      macos_binary_url:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

env:
  REGISTRY: ghcr.io

jobs:

  build-and-publish-image:
    name: Build and publish Taqeria Docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
       include:
         - binary: "${{ inputs.linux_binary_url }}"
           docker_platform: "linux/amd64"
         - binary: "${{ inputs.macos_binary_url }}"
           docker_platform: "linux/arm64/v8"
    env:
      DENO_TARGET: ${{ matrix.deno_target }}

    steps:
      - name: Download the binary
        run: wget ${{ needs.build-binaries.outputs.public-url-ubuntu }} -O taq
          

      - name: Registry login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get short SHA
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        id: "vars"
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short $GITHUB_SHA)"
          echo "::set-output name=taq_version::`echo ${GITHUB_REF_NAME/\//-}`"

      - name: Extract metadata
        id: image-metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/taqueria
          tags: |
            type=ref,event=branch
            type=ref,event=pr,suffix=-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=${{ steps.vars.outputs.taq_version }}-${{ steps.vars.outputs.short_sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.docker_platform }}
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}

      # - name: Comment on PR
      #   if: ${{ github.event_name == 'pull_request' }}
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'The `taqueria` docker image has been published and is avaiable [here](https://github.com/ecadlabs/taqueria/pkgs/container/taqueria). Look for the image with the tag `pr-${{ github.event.number }}-${{ steps.vars.outputs.short_sha }}`. The image is available for the following platforms: `linux/amd64` and `linux/arm64/v8`.' 
      #       })