on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      id: install-node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm install

    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
      
    - run: npm test
      if: runner.os != 'Linux'
